import esbuild from 'esbuild';
import process from 'process';
import builtins from 'builtin-modules';
import fs from 'fs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const TEST_VAULT = 'test-vault/.obsidian/plugins/obsidian-ankisync';

// Ensure test vault directory exists
fs.mkdirSync(TEST_VAULT, { recursive: true });

import path from 'path';

const WASM_SRC = 'node_modules/@bokuweb/zstd-wasm/dist/common/zstd.wasm';
const SQL_WASM_SRC = 'node_modules/sql.js/dist/sql-wasm.wasm';

// Copy static files
function copyFiles() {
	fs.copyFileSync('manifest.json', TEST_VAULT + '/manifest.json');
	if (fs.existsSync('styles.css')) {
		fs.copyFileSync('styles.css', TEST_VAULT + '/styles.css');
	}
	// Copy zstd WASM alongside the bundle so init() can find it at runtime
	if (fs.existsSync(WASM_SRC)) {
		fs.copyFileSync(WASM_SRC, TEST_VAULT + '/zstd.wasm');
	}
	// Copy sql.js WASM alongside the bundle
	if (fs.existsSync(SQL_WASM_SRC)) {
		fs.copyFileSync(SQL_WASM_SRC, TEST_VAULT + '/sql-wasm.wasm');
	}
}

copyFiles();

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: ['obsidian', 'electron', ...builtins],
	format: 'cjs',
	minify: prod,
	target: 'es2020',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: TEST_VAULT + '/main.js',
	plugins: [
		{
			name: 'copy-on-rebuild',
			setup(build) {
				build.onEnd(() => {
					copyFiles();
				});
			},
		},
	],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
